apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-dev2
  namespace: argocd
spec:
  # The project the application belongs to.
  project: default
  # Source of the application manifests
  source:
    repoURL: https://github.com/alaghusundhar/sundar-argocd-apps.git
    targetRevision: master
    path: overlays/dev2
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
   automated:
     selfHeal: true
     prune: true